### ISSUE TITLE
[Idea] Steal/Borrow the MonadRec idea from Purescript

### ISSUE THREAD

**Issue by clinuxrulz** [DanielGronau/highj#12]
Purescript is one of those languages that is like Haskell and compiles to JavaScript.

Javascript has no TCO just like Java.

Purescript has a novel solution of MonadRec (which is possible to define for ALL monads), that gives us TCO back (stops consuming additional stack with each recursion.)

https://pursuit.purescript.org/packages/purescript-tailrec/0.3.1/docs/Control.Monad.Rec.Class

We should probably credit Phil Freeman in the source header if we use it.

**Comment by DanielGronau** [comment]
I've coded something, but I'm not sure I got it right, or that I even understand the implications correctly.

For Maybe I implemented it by using a simple while loop, which was easy enough. Of course the more interesting use case are monad transformers, but I guess that flies way over my head.

What do you think?

**Comment by clinuxrulz** [comment]
Yes, thats the idea. Non-transformer monads can just use while loops for their ```MonadRec```.

I have a ```MonadRec``` instance for the RWST monad in some code from work to give an idea of how to do it for transformers.

We're able to browse the source code of purescripts libraries if we need hints too.

I'll track down that RWST code.

**Comment by clinuxrulz** [comment]
Also ```Foldable``` and ```Traversable``` typeclasses do ***not*** need to change to take advantage of ```tailRecM```. I have another trick for that sort of thing.
see example from: https://pursuit.purescript.org/packages/purescript-stackless/0.0.3 .

**Comment by DanielGronau** [comment]
I added MonadRec to ListMonadPlus. I implemented it by iterating and flatMapping over and over until there are no more Lefts in the list. Maybe you could have a look if it makes some sense.

**Comment by clinuxrulz** [comment]
Yes. The implementation appears to be correct. That one is rather interesting, it feels like green-threads.

**Comment by DanielGronau** [comment]
Are there types left which need a MonadRec instance, or can this be closed?

**Comment by clinuxrulz** [comment]
```SafeIO```, ```IO``` and ```Effect``` that I can think of.

**Comment by DanielGronau** [comment]
`IO` had already a `MonadRec` instance, I copied it for `SafeIO`. `Effect1` is no monad. Or do you mean something different with `Effect`?

**Comment by clinuxrulz** [comment]
Ah! Sorry, you are correct. We can close this one.
