### ISSUE TITLE
Do Notation revisited

### ISSUE THREAD

**Issue by clinuxrulz** [DanielGronau/highj#13]
I have another approach that lets the user use their own variable names, rather than `A` to `Z`.

Here is a test of the new syntax:

```
public class Main {
    public static void main(String[] params) {
        System.out.println(test1().toString());
        System.out.println(test2().toString());
    }
    
    public static Maybe<Integer> test1() {
        MContext<Maybe.µ> ctx = do_(Maybe.monad);
        MValue<Integer> myVar1 = ctx.assign(Maybe.newJust(3));
        MValue<Integer> myVar2 = ctx.assign(Maybe.newJust(5));
        MValue<Integer> myVar3 = ctx.let2(myVar1, myVar2, (Integer a, Integer b) -> a + b);
        return Maybe.narrow(ctx.doneRes(myVar3));
    }
    
    public static Maybe<Integer> test2() {
        MContext<Maybe.µ> ctx = do_(Maybe.monad);
        MValue<Integer> myVar1 = ctx.assign(Maybe.newJust(3));
        MValue<Integer> myVar2 = ctx.assign(Maybe.newJust(5));
        ctx.seq(Maybe.newNothing());
        MValue<Integer> myVar3 = ctx.let2(myVar1, myVar2, (Integer a, Integer b) -> a + b);
        return Maybe.narrow(ctx.doneRes(myVar3));
    }
}
```

And the implementation link:
https://github.com/clinuxrulz/DoNotation/blob/master/src/main/java/gmail/clinuxrulz/donotation/Do.java

It had to move from the fluent interface to programmable semi-collins in order to work.

Still not perfect, but let me know what you think.

**Comment by clinuxrulz** [comment]
I've made a slight change to stop someone from using a binded value in the wrong context. But it did cost me some extra noise.

The test now looks like so:
```
public class Main {
    public static void main(String[] params) {
        System.out.println(test1().toString());
        System.out.println(test2().toString());
    }
    
    public static Maybe<Integer> test1() {
        return Maybe.narrow(do_(Maybe.monad, new DoBlock<Maybe.µ,Integer>() {
            @Override
            public <H> _<Maybe.µ, Integer> run(MContext<H, Maybe.µ> ctx) {
                MValue<H,Integer> myVar1 = ctx.assign(Maybe.newJust(3));
                MValue<H,Integer> myVar2 = ctx.assign(Maybe.newJust(5));
                MValue<H,Integer> myVar3 = ctx.let2(myVar1, myVar2, (Integer a, Integer b) -> a + b);
                return ctx.doneRes(myVar3);
            }
        }));
    }
    
    public static Maybe<Integer> test2() {
        return Maybe.narrow(do_(Maybe.monad, new DoBlock<Maybe.µ,Integer>() {
            @Override
            public <H> _<Maybe.µ, Integer> run(MContext<H, Maybe.µ> ctx) {
                MValue<H,Integer> myVar1 = ctx.assign(Maybe.newJust(3));
                MValue<H,Integer> myVar2 = ctx.assign(Maybe.newJust(5));
                ctx.seq(Maybe.newNothing());
                MValue<H,Integer> myVar3 = ctx.let2(myVar1, myVar2, (Integer a, Integer b) -> a + b);
                return ctx.doneRes(myVar3);
            }
        }));
    }
}
```

The ```H``` stops the ```MValue``` from being used in the wrong ```MContext```.

**Comment by DanielGronau** [comment]
Hello Clinton,

I like the new notation, and I think the extra noise isn't too bad. And 
H is a phantom type, right?

I tried the code, and it seems to work really well (although I don't 
understand all details), so if you like you this could replace the old 
do-notation (which is already pretty cool).

Cheers,
Daniel

Am 30.04.2016 um 11:41 schrieb Clinton Selke:
>
> I've made a slight change to stop someone from using a binded value in 
> the wrong context. But it did cost me some extra noise.
>
> The test now looks like so:
>
> |public class Main { public static void main(String[] params) { 
> System.out.println(test1().toString()); 
> System.out.println(test2().toString()); } public static Maybe<Integer> 
> test1() { return Maybe.narrow(do_(Maybe.monad, new 
> DoBlock<Maybe.µ,Integer>() { @Override public <H> _<Maybe.µ, Integer> 
> run(MContext<H, Maybe.µ> ctx) { MValue<H,Integer> myVar1 = 
> ctx.assign(Maybe.newJust(3)); MValue<H,Integer> myVar2 = 
> ctx.assign(Maybe.newJust(5)); MValue<H,Integer> myVar3 = 
> ctx.let2(myVar1, myVar2, (Integer a, Integer b) -> a + b); return 
> ctx.doneRes(myVar3); } })); } public static Maybe<Integer> test2() { 
> return Maybe.narrow(do_(Maybe.monad, new DoBlock<Maybe.µ,Integer>() { 
> @Override public <H> _<Maybe.µ, Integer> run(MContext<H, Maybe.µ> ctx) 
> { MValue<H,Integer> myVar1 = ctx.assign(Maybe.newJust(3)); 
> MValue<H,Integer> myVar2 = ctx.assign(Maybe.newJust(5)); 
> ctx.seq(Maybe.newNothing()); MValue<H,Integer> myVar3 = 
> ctx.let2(myVar1, myVar2, (Integer a, Integer b) -> a + b); return 
> ctx.doneRes(myVar3); } })); } } |
>
> The |H| stops the |MValue| from being used in the wrong |MContext|.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/DanielGronau/highj/issues/13#issuecomment-215949494>
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by clinuxrulz** [comment]
I believe ```H``` is called a skolem type variable (but don't quote me on that. The same trick is used in the ST monad in Haskell, in order to stop a STRef from being used in the wrong.

I'll make the new do-notation a little more complete 1st, then introduce it later. (let0, let1, let2, ... etc.)

**Comment by clinuxrulz** [comment]
I've sort of got an explanation of how it works. You can think of do-notation as a imperative programming language with a list of statements (kind of like Javascript). Such programs you can represent as a list of statements, hence the ```ArrayList```. The last things that were needed was support for variables, and the ability to generate fresh variable names. Those last two things can be seen through the use of the state monad transformer (for variables) and ```newMValue``` (the fresh variable names).

The implementation was inspired by ```Sunroof``` library for Haskell the does something similar sort of think to make a JavaScript Monad (when the monad is executed it produces JavaScript code.)

I'll close this issue for now, because I think it is complete. We can re-open if there are more things to sort out.
