### ISSUE TITLE
IntMap (Persistant version)

### ISSUE THREAD

**Issue by clinuxrulz** [DanielGronau/highj#21]

**Comment by DanielGronau** [comment]
@clinuxrulz I changed the test case to a random insert order, and it fails.

**Comment by clinuxrulz** [comment]
OK, I'll have a look into this later. Thanks for the test.

**Comment by clinuxrulz** [comment]
insert() bug is now fixed, and test passes. Will need to test delete() too at some stage.

**Comment by DanielGronau** [comment]
Thank you for the quick fix! 

I made some small changes on IntMap, I hope this is okay. I had the following observations: 
- `size()` is missing
- `lookup(int key, A defaultValue)` would be convenient (to avoid Maybe creation) 
- something iterable (`T2(Integer, A)` ?) would be good
- There are a lot of `null` checks, maybe it is more convenient to fill the `nodes` Array initially with `EMPTY`? This shouldn't have a big space or performance impact.

**Comment by clinuxrulz** [comment]
All those suggestions sound good to me. Go for it.

**Comment by clinuxrulz** [comment]
I have an idea that can make creating Java a ```Iterable``` easier.

We could defined a ```Generator``` or ```GeneratorT``` monad that has a special method called ```yeild(A a)```. We could then recursively traverse a tree with the generator calling yeild on each leaf. Then once we are done you can call the generator's ```toJavaIterable()``` method to produce an ```Iterable```.

The generator can be thought of as a JavaScript generator function (```function*()``` in JavaScript)

Its sort of a special helper monad that we may not wish to let the end user use. Maybe under ```highj.impl```, and tell users in the documentation not to use anything under ```highj.impl```.

**Comment by clinuxrulz** [comment]
Here is a sample ```GeneratorT```, would need to change it a bit for highj.

https://gist.github.com/clinuxrulz/7cab6c54e53e49ad217de069a5a555e5

**Comment by clinuxrulz** [comment]
IntMap.iterator() has been solved in #27 if there is no objections. It also has a bug fix for ```Monad.sequence_```.

**Comment by DanielGronau** [comment]
Thank you!

**Comment by DanielGronau** [comment]
I close the issue for now, although we should have another look at the API, JavaDoc etc later
