### ISSUE TITLE
Make Either, Maybe and F1 derive4j-ready

### ISSUE THREAD

**Issue by DanielGronau** [DanielGronau/highj#23]
See https://github.com/derive4j/derive4j/issues/32

This overlaps with the package structure issue #18, but is more urgent.

Here is my suggestions:

- move the `org.highj.data.collection` package to `org.highj.collection`
- move the `org.highj.data.functions` package to `org.highj.function`
- change the constructor methods in `Either` to `Left()` and `Right()`
- change the constructor methods in `Maybe` to `Just()` and `Nothing()`
- I really hate to write "lazy" all over the place, so I would suggest to indicate laziness throughout the library by the suffix $, which would give us `Either.Left$()`, `Either.Right$()` and `Maybe.Just$()`. I'd rather use the underscore, but it would clash with Haskell function names like `sequence_`. Of course I'm open for other suggestions.

org.highj.collection.Either, org.highj.collection.Maybe and org.highj.function.F1

**Comment by clinuxrulz** [comment]
I'm a little uncomfortable with ```Either``` being considered as a collection. But at the same time don't want it to sit alone.

**Comment by DanielGronau** [comment]
Good point. We could use a wider package name (actually `data` might be not too bad), or we could group all the "wrappy" stuff (`Either`, `Maybe`, tuples, `Mutable`, `Lazy`...) together.

**Comment by clinuxrulz** [comment]
I like ```data```.

Means?

org.highj.data.Either
org.highj.data.List
org.highj.data.Map

etc.

**Comment by DanielGronau** [comment]
When the dust around `IntMap` has settled, I would like to squeeze these package changes in. I think we could live with a partial solution for 0.8, just for collections. So I would move all classes in `...data.collection` to `...data`. However, I don't want to move all the instance packages like `...data.collection.maybe` a level up, which would be confusing for users (as then these packages would be side by side with other stuff like tuples). Maybe we should just rename them to `...data.instance.maybe` etc. The remaining packages could be sorted out later under issue #18. What do you think?

**Comment by clinuxrulz** [comment]
I say yes. And use ```...data.instance.maybe``` for now. ```TreeMap``` will be a little tricky to implement, we could delay it for 0.9 so we can get a 0.8 release out sooner.

I believe the derive4j guys are gonna do automatic generation of the narrow methods which will be interesting. Java becoming more like Haskell each day.

Its tempting to just borrows Haskell's or PureScrpt's package layout. E.g. ```org.highj.data.*``` for data holding types, and ```org.highj.control.*``` for control flow types (like IO and ErrorT). How would you feel about that? IDE refactoring tool make it easy to try out different layouts.

**Comment by DanielGronau** [comment]
`TreeMap` could be a simple BST for now, similar to `Map`. Of course a more sophisticated implementation with balancing should follow soon.

**Comment by DanielGronau** [comment]
@clinuxrulz I moved and renamed stuff according to plan, maybe you can have a look before I notify the derive4j team.

**Comment by clinuxrulz** [comment]
Looks great! That should be enough for their HighJ flavoured annotation.
