### ISSUE TITLE
List-Zipper

### ISSUE THREAD

**Issue by DanielGronau** [DanielGronau/highj#25]
We need simple `Zipper` class for `List`s, allowing efficient access of a focused area.

**Comment by DanielGronau** [comment]
Added an implementation, but JavaDoc and tests are still missing

**Comment by DanielGronau** [comment]
Good enough, I hope...

**Comment by clinuxrulz** [comment]
It looks good.

**Comment by clinuxrulz** [comment]
Almost. Travis CI fails on one of the Zipper tests.
https://travis-ci.org/DanielGronau/highj/builds/133240484

I'm sure its something minor. However I do not have time to look at it right now. I'll leave it with you.

**Comment by DanielGronau** [comment]
Hmmm, I have problems fixing this from work, for some reason I get compiler errors in OS X, even after JDK update. Has to wait until evening.

**Comment by clinuxrulz** [comment]
More bug reports for Oracle :smile:

**Comment by clinuxrulz** [comment]
All fixed #34

**Comment by DanielGronau** [comment]
Thank you!

Mental note: No more commits after midnight...
