### ISSUE TITLE
Choose a license and add a LICENSE file.

### ISSUE THREAD

**Issue by clinuxrulz** [DanielGronau/highj#38]
This will become important so that others can use this code legally.

This site might help with choosing one: http://choosealicense.com/

**Comment by DanielGronau** [comment]
I thought I already had to decide for license when copying the project over from Google Code, but apparently that was not the case. I would go with MIT or Apache 2, what do you think?

**Comment by clinuxrulz** [comment]
I like MIT, its nice and simple.
Apache is a little painful, because anyone who uses the code has to state all the changes they made to the code.

**Comment by DanielGronau** [comment]
Added MIT license using addalicense.com - pretty cool site, BTW
