### ISSUE TITLE
Do we need Try and/or Validation?

### ISSUE THREAD

**Issue by DanielGronau** [DanielGronau/highj#41]
Of course, `Try` can be simulated with `Either<Exception, T>`, but without convenience methods it's just... inconvenient. Similar, `Validation` could be simulated as `Either<List<Exception>, T>`, also not great. And of course, both types could interact, when we have them.

**Comment by jbgi** [comment]
```Validation``` is useful if only to separate the error accumulation api that would make Either a bit overweight.
But ```Try``` is not useful, because there is already an IO type where one can catch exceptions; better enrich the IO api with things like ```bracket```.

**Comment by DanielGronau** [comment]
Good point!
