### ISSUE TITLE
Should we drop Kleisli and related classes?

### ISSUE THREAD

**Issue by DanielGronau** [DanielGronau/highj#43]
Because according to http://typeclassopedia.bitbucket.org/#slide-114 it is the same as `ReaderT`, and looking at both from a distance while squinting seems to support this claim. 

As `ReaderT` is clearly more elaborate, fits in the monad transformer pattern and is better known under this name, I'd decide against good old `Kleisli`.

BTW, we have also a `Cokleisli`, could this be isomorphic to `WriterT`?

**Comment by clinuxrulz** [comment]
```Kleisli``` is more to do with Arrows than Monads. Its embeds monadic computations in arrows.

It is sort of like an effectfull arrow interface. It has a different purpose than ```ReaderT```, so I think we should keep it.

**Comment by clinuxrulz** [comment]
It is true that they are equivalent. But you can use the type-name to express intent.

**Comment by clinuxrulz** [comment]
And actually you can not directly write an ```Arrow``` instance for ```ReaderT```, because its ```ReaderT r m a```, you would need a wrapper class. Its another reason to keep ```Kleisli```.

**Comment by DanielGronau** [comment]
Okay, so we keep it. Thanks for the clarification!
